[[redirects]]
  from = "/info"
  to = "https://www.lopp.net/bitcoin-information.html"
  status = 302

[[redirects]]
  from = "/dev"
  to = "https://bitcoindev.network/"
  status = 302

[[redirects]]
  from = "/saylor"
  to = "https://www.strategy.com/"
  status = 302

[[redirects]]
  from = "/bitcoinorg"
  to = "https://bitcoin.org/en/resources"
  status = 302

[[redirects]]
  from = "/*"
  to = "/bitcoinorg"
  status = 302
